export const ROLES = [
  'PLATFORM_SUPER_ADMIN',
  'TENANT_OWNER',
  'TENANT_ADMIN',
  'HR_ADMIN',
  'PAYROLL_ADMIN',
  'BRANCH_MANAGER',
  'DEPARTMENT_MANAGER',
  'SUPERVISOR',
  'EMPLOYEE',
  'AUDITOR',
  'DEVICE_ADMIN',
  'ACCESS_CONTROL_ADMIN',
] as const;

export type Role = (typeof ROLES)[number];

export const PERMISSIONS = [
  'tenant.manage',
  'org.read',
  'org.write',
  'branch.read',
  'branch.write',
  'department.read',
  'department.write',
  'location.read',
  'location.write',
  'user.read',
  'user.write',
  'role.read',
  'role.write',
  'employee.read',
  'employee.write',
  'employee.delete',
  'employee.salary.read',
  'employee.salary.write',
  'device.read',
  'device.write',
  'device.delete',
  'device.ingest',
  'attendance.read',
  'attendance.write',
  'attendance.correction',
  'attendance.approve',
  'attendance.recalculate',
  'shift.read',
  'shift.write',
  'roster.read',
  'roster.write',
  'holiday.read',
  'holiday.write',
  'leave.read',
  'leave.write',
  'leave.approve',
  'overtime.read',
  'overtime.write',
  'overtime.approve',
  'payroll.read',
  'payroll.write',
  'payroll.run',
  'payroll.approve',
  'payroll.lock',
  'payroll.export',
  'payslip.read',
  'access.read',
  'access.write',
  'visitor.read',
  'visitor.write',
  'notification.read',
  'notification.write',
  'report.read',
  'report.export',
  'audit.read',
  'integration.read',
  'integration.write',
  'ai.chat',
  'ai.analytics',
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ALL_PERMISSIONS = PERMISSIONS as readonly string[];

const tenantAdminScoped = [
  'tenant.manage',
  'org.read',
  'org.write',
  'branch.read',
  'branch.write',
  'department.read',
  'department.write',
  'location.read',
  'location.write',
  'user.read',
  'user.write',
  'role.read',
  'role.write',
  'employee.read',
  'employee.write',
  'employee.delete',
  'employee.salary.read',
  'employee.salary.write',
  'device.read',
  'device.write',
  'device.delete',
  'device.ingest',
  'attendance.read',
  'attendance.write',
  'attendance.correction',
  'attendance.approve',
  'attendance.recalculate',
  'shift.read',
  'shift.write',
  'roster.read',
  'roster.write',
  'holiday.read',
  'holiday.write',
  'leave.read',
  'leave.write',
  'leave.approve',
  'overtime.read',
  'overtime.write',
  'overtime.approve',
  'payroll.read',
  'payroll.write',
  'payroll.run',
  'payroll.approve',
  'payroll.lock',
  'payroll.export',
  'payslip.read',
  'access.read',
  'access.write',
  'visitor.read',
  'visitor.write',
  'notification.read',
  'notification.write',
  'report.read',
  'report.export',
  'audit.read',
  'integration.read',
  'integration.write',
  'ai.chat',
  'ai.analytics',
];

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, readonly string[]> = {
  PLATFORM_SUPER_ADMIN: ALL_PERMISSIONS,
  TENANT_OWNER: tenantAdminScoped,
  TENANT_ADMIN: tenantAdminScoped,
  HR_ADMIN: [
    'employee.read',
    'employee.write',
    'employee.delete',
    'employee.salary.read',
    'employee.salary.write',
    'user.read',
    'attendance.read',
    'attendance.write',
    'attendance.correction',
    'attendance.approve',
    'attendance.recalculate',
    'shift.read',
    'shift.write',
    'roster.read',
    'roster.write',
    'holiday.read',
    'holiday.write',
    'leave.read',
    'leave.write',
    'leave.approve',
    'overtime.read',
    'overtime.write',
    'overtime.approve',
    'report.read',
    'report.export',
    'notification.read',
    'notification.write',
  ],
  PAYROLL_ADMIN: [
    'employee.read',
    'employee.salary.read',
    'employee.salary.write',
    'attendance.read',
    'leave.read',
    'overtime.read',
    'overtime.approve',
    'payroll.read',
    'payroll.write',
    'payroll.run',
    'payroll.approve',
    'payroll.lock',
    'payroll.export',
    'payslip.read',
    'report.read',
    'report.export',
    'audit.read',
  ],
  BRANCH_MANAGER: [
    'employee.read',
    'employee.write',
    'attendance.read',
    'attendance.write',
    'attendance.correction',
    'attendance.approve',
    'shift.read',
    'roster.read',
    'holiday.read',
    'leave.read',
    'leave.approve',
    'overtime.read',
    'overtime.approve',
    'report.read',
    'notification.write',
    'visitor.read',
    'visitor.write',
  ],
  DEPARTMENT_MANAGER: [
    'employee.read',
    'attendance.read',
    'shift.read',
    'roster.read',
    'holiday.read',
    'leave.read',
    'leave.approve',
    'overtime.read',
    'overtime.approve',
    'report.read',
  ],
  SUPERVISOR: [
    'employee.read',
    'attendance.read',
    'leave.read',
    'leave.approve',
    'overtime.read',
    'overtime.approve',
    'report.read',
  ],
  EMPLOYEE: [
    'employee.read',
    'attendance.read',
    'leave.read',
    'leave.write',
    'overtime.read',
    'overtime.write',
    'payslip.read',
    'ai.chat',
    'notification.read',
  ],
  AUDITOR: [
    'audit.read',
    'report.read',
    'report.export',
    'payroll.read',
    'attendance.read',
  ],
  DEVICE_ADMIN: [
    'device.read',
    'device.write',
    'device.delete',
    'device.ingest',
    'attendance.read',
    'integration.read',
  ],
  ACCESS_CONTROL_ADMIN: [
    'access.read',
    'access.write',
    'visitor.read',
    'device.read',
    'report.read',
  ],
};

export const EMPLOYMENT_STATUSES = [
  'ACTIVE',
  'ON_LEAVE',
  'SUSPENDED',
  'TERMINATED',
  'REHIRED',
] as const;

export const IDEMPOTENCY_HEADER = 'Idempotency-Key';